### PR TITLE
Fix/issue 77 report title not substituted

### PR DESCRIPTION
**Pull request by imda-amdlahir**
## Description

This PR fixes [issue-77](https://github.com/IMDA-BTG/aiverify/issues/77) where report title global variable is not substituted with its value when used on report.

## Motivation and Context

The root cause of this is global vars created in memory from project info at project creation is not saved in DB.
Code changes in the fix:
- create the global variables from project info at project creation for both `blank template` and `use template` projects.
- challenge
The reducers have no `await promise mechanism` so execution cannot await DB saves. Also, all save to DB methods in the custom dispatch methods are debounced for 5 seconds.
- solution
Provide a `callback fn argument` to the dispatch action so that this fn will be called only after variables are saved to DB. This solved a problem where after creating a project from template, the toolkit routes user by full page refresh, to the canvas screen without waiting for global vars to be saved. However, this caused a delay of 5 seconds before the routing is invoked and user has to wait for 5 seconds on the template screen after clicking next button. Debounce flush() method just doesn't work here too. So the only solution to fix this delay is to create a non debounced version of globalVars save method and use it on project creation.

Some cleanups of commented out codes were also done

## Type of Change

- fix: A bug fix

### use blank template
1. Create a project using `blank` template
2. Add a few heading widgets to canvas.
3. Populate the heading texts using global variables (name, reportTitle, company, description)
4. Generate report and check that the headings are printed accordingly

### use existing template
1. Create a project using `existing` template
2. Add a few heading widgets to canvas.
3. Populate the heading texts using global variables (name, reportTitle, company, description)
4. Generate report and check that the headings are printed accordingly

## Checklist

Please check all the boxes that apply to this pull request using "x":

- [x ]  I have tested the changes locally and verified that they work as expected.
- [ ]  I have added or updated the necessary documentation (README, API docs, etc.).
- [ ]  I have added appropriate unit tests or functional tests for the changes made.
- [ ]  I have followed the project's coding conventions and style guidelines.
- [ x]  I have rebased my branch onto the latest commit of the main branch.
- [ ]  I have squashed or reorganized my commits into logical units.
- [ ]  I have added any necessary dependencies or packages to the project's build configuration.
- [x ]  I have performed a self-review of my own code.
- [x ]  I have read, understood and agree to the Developer Certificate of Origin below, which this project utilises.

## Screenshots (if applicable)

[If the changes involve visual modifications, include screenshots or GIFs that demonstrate the changes.]

## Additional Notes

[Add any additional information or context that might be relevant to reviewers.]

<details>
  <summary>Developer Certificate of Origin</summary>

 ```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
 ```
</details>

### CODE REVIEW

**Comment by imda-amdlahir** [comment]
@imda-benedictlee 
Similar to previous PRs, pre-merge checks is red because lint and unit tests code coverage has not met threshold. These works are happening in separate branches.

**Review by imda-benedictlee — APPROVED** [review]
Approved

**Comment by imda-benedictlee** [comment]
Tested Fix. Issue has been fixed. Generated Report contains Report Title.

image

**Comment by imda-benedictlee** [comment]
Tested with AI Verify Report Template. Working as expected. Report Generated. Screenshot attached.

image

**Comment by imda-benedictlee** [comment]
Tested on Docker. Working as expected. Screenshot Attached.

image

**Review by kimeetok — APPROVED** [review]

**Comment by imda-benedictlee** [comment]
Tested on Docker. Working as expected. Screenshot attached.

image

**Pull request merged**
