### PR TITLE
Fix/scr 009

### PR DESCRIPTION
**Pull request by imda-peckyoke**
## Description

Update the portal graphql client so that all browser requests uses the portal rewrites for graphql client requests and subscriptions. Graphql URL are automatically formatted using the window.location hostname and port, so that WS connections connect to the right hostname instead of default localhost. 

This fix should also resolve issue: https://github.com/IMDA-BTG/aiverify/issues/169

The follow variables are remove from portal .env.development:
NEXT_PUBLIC_SERVER_URL, NEXT_PUBLIC_WEBSOCKET_URL, SERVER_URL, WEBSOCKET_URL
Only NEXT_PUBLIC_WEBSOCKET_URL is still in use but it should be set only if the websocket URL need to be hardcoded.

## Motivation and Context

[Explain the motivation or the context behind this pull request. Why is it necessary?]

## Type of Change

fix:
The portal graphql URL should now be set correctly without having to set the SEVER_URL and WEBSOCKET_URL env.

## How to Test

Deploy and run the ai-verify-apigw and ai-verify-portal on one server. Access the portal from another PC or laptop and observe the http requests to make sure there's no connection errors.

## Checklist

Please check all the boxes that apply to this pull request using "x":

- [ x]  I have tested the changes locally and verified that they work as expected.
- [ ]  I have added or updated the necessary documentation (README, API docs, etc.).
- [ ]  I have added appropriate unit tests or functional tests for the changes made.
- [x ]  I have followed the project's coding conventions and style guidelines.
- [x]  I have rebased my branch onto the latest commit of the main branch.
- [ ]  I have squashed or reorganized my commits into logical units.
- [ ]  I have added any necessary dependencies or packages to the project's build configuration.
- [x]  I have performed a self-review of my own code.
- [x]  I have read, understood and agree to the Developer Certificate of Origin below, which this project utilises.

## Screenshots (if applicable)

[If the changes involve visual modifications, include screenshots or GIFs that demonstrate the changes.]

## Additional Notes

[Add any additional information or context that might be relevant to reviewers.]

<details>
  <summary>Developer Certificate of Origin</summary>

 ```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
 ```
</details>

### CODE REVIEW

**Review by thomasimda — APPROVED** [review]

**Comment by imda-benedictlee** [comment]
Integration Test for Frontend Passed. Screenshot attached:
Screenshot 2023-12-26 at 11 30 05 AM

**Review by imda-benedictlee — APPROVED** [review]
Approve & Reviewed Code

**Comment by imda-benedictlee** [comment]
Smoke Test for Docker Passed. Report Attached:
[Smoke Test Report For Docker.zip](https://github.com/IMDA-BTG/aiverify/files/13770843/Smoke.Test.Report.For.Docker.zip)

**Comment by imda-benedictlee** [comment]
Pipeline Test for Docker Passed. Screenshot Attached.
[Pipeline Tests For Docker Screenshots.zip](https://github.com/IMDA-BTG/aiverify/files/13771165/Pipeline.Tests.For.Docker.Screenshots.zip)

**Pull request merged**
