### PR TITLE
Fix Issue 153 - await all flushed debounced update functions before generate report

### PR DESCRIPTION
**Pull request by imda-amdlahir**
## Description

Code changes to fix [issue 153](https://github.com/IMDA-BTG/aiverify/issues/153)

Code changes includes:

In project/projectTemplate contexts codes;
- update all `_send<updates>` debounced functions to return the promises that they create.
- adding `_sendModelAndDatasets` debounced method to the list of all debounced functions.
- introduced `flushAllUpdatesAsync` method which awaits all the `_send<updates>` when debounced is flushed.
- `generateReport` method awaits `flushAllUpdatesAsync` before proceeding to generate report. This should ensure all save operation are completed first.

Also cleaned up some commented out codes.

## Motivation and Context

This PR fixes an issue where generate report operation executes before model and datasets which are saved in frontend cache is, not yet saved in db.

## Type of Change

fix: A bug fix

## How to Test

1) Follow Reproduction steps in [issue 153](https://github.com/IMDA-BTG/aiverify/issues/153)
2) Regression needed -
Test that `projectInfo`, `pages`, `globalVars`, `modelAndDatasets`, `testInformationData` and `inputBlockData` fields are saved normally in the `projectTemplateModel db`

## Checklist

Please check all the boxes that apply to this pull request using "x":

- [x ]  I have tested the changes locally and verified that they work as expected.
- [ ]  I have added or updated the necessary documentation (README, API docs, etc.).
- [ ]  I have added appropriate unit tests or functional tests for the changes made.
- [ ]  I have followed the project's coding conventions and style guidelines.
- [x ]  I have rebased my branch onto the latest commit of the main branch.
- [ x]  I have squashed or reorganized my commits into logical units.
- [ ]  I have added any necessary dependencies or packages to the project's build configuration.
- x[ ]  I have performed a self-review of my own code.
- [ ]  I have read, understood and agree to the Developer Certificate of Origin below, which this project utilises.

<details>
  <summary>Developer Certificate of Origin</summary>

 ```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
 ```
</details>

### CODE REVIEW

**Review by kimeetok — APPROVED** [review]

**Review by imda-peckyoke — APPROVED** [review]
okay

**Comment by imda-benedictlee** [comment]
Able to proceed with testing ALE with no issues:
image

image

Able to proceed with testing PDP with no issues:
image

image

**Comment by imda-amdlahir** [comment]
@imda-benedictlee @imda-kwokwk 
Regarding pre-merged checks that failed -

1) Unit tests with coverage
Is the exit code 1 caused by coverage threshold not met? All existing tests passed. Increasing code coverage is work-in-progress in a separate branch.

2) Lint check
Fixes are in progress, in separate branch

3) Vulnerability
As discussed before, please exclude dev dependencies from the script.

**Comment by imda-benedictlee** [comment]
Smoke Test Passed
image

**Pull request merged**
