### PR TITLE
Test & Merge for Release v0.9.2

### PR DESCRIPTION
**Pull request by imda-benedictlee**
## Description

Test & Merge for Release v0.9.2

## Motivation and Context

Major bug fixes & Python 3.11 support
- Setup scripts will now run python 3.11
- Fixed bug where some test runs are stuck (#135)
- Fixed error in process checklist numbering in report (#124)
- Vulnerability fixes

## Type of Change

feat: A new feature
fix: A bug fix

## How to Test

- Integration Test
- Test Models and Datasets

## Checklist

Please check all the boxes that apply to this pull request using "x":

- [x]  I have tested the changes locally and verified that they work as expected.
- [ ]  I have added or updated the necessary documentation (README, API docs, etc.).
- [ ]  I have added appropriate unit tests or functional tests for the changes made.
- [x]  I have followed the project's coding conventions and style guidelines.
- [x]  I have rebased my branch onto the latest commit of the main branch.
- [ ]  I have squashed or reorganized my commits into logical units.
- [x]  I have added any necessary dependencies or packages to the project's build configuration.
- [x]  I have performed a self-review of my own code.
- [x]  I have read, understood and agree to the Developer Certificate of Origin below, which this project utilises.

## Screenshots (if applicable)

Screenshots are attached below.

## Additional Notes

None

<details>
  <summary>Developer Certificate of Origin</summary>

 ```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
 ```
</details>

### CODE REVIEW

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.ensemble._bagging.BaggingClassifier.sav for Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_sklearn.ensemble._forest.RandomForestClassifier.sav for Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_sklearn.linear_model._base.LinearRegression.sav with Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.tree._classes.DecisionTreeClassifier.sav with Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Test binary_classification_compas_sklearn.tree._classes.DecisionTreeClassifier.sav with Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_sklearn.ensemble._forest.ExtraTreesRegressor.sav for Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_sklearn.ensemble._gb.GradientBoostingRegressor.sav for Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.ensemble._gb.GradientBoostingClassifier.sav for Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Test regression_insurance_sklearn.ensemble._forest.RandomForestRegressor.sav for Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Test multiclass_classification_loan_sklearn.ensemble._forest.RandomForestClassifier.sav for Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_sklearn.ensemble._forest.RandomForestClassifier.sav for Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.ensemble._bagging.BaggingClassifier.sav with Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_sklearn.ensemble._bagging.BaggingClassifier.sav for Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.linear_model._perceptron.Perceptron.sav for Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_sklearn.linear_model._perceptron.Perceptron.sav for Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_categoricalcrossentropy_keras.engine.sequential.Sequential.sav for Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_hinge_keras.engine.sequential.Sequential.sav for Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_xgboost.sklearn.XGBClassifier.sav for Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_xgboost.sklearn.XGBClassifier.sav with Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_xgboost.sklearn.XGBRegressor.sav for Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_crossentropy_keras.engine.sequential.Sequential.sav for Build Script. Working as expected. Report Generated.

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_logistic_xgboost.core.Booster.sav for Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_lightgbm.sklearn.LGBMClassifier.sav for Build Script. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.ensemble._bagging.BaggingClassifier.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Test binary_classification_compas_sklearn.ensemble._forest.RandomForestClassifier.sav for Docker. Working as expected. Report Generated.

**Comment by imda-benedictlee** [comment]
Test regression_insurance_sklearn.linear_model._base.LinearRegression.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Test multiclass_classification_loan_sklearn.tree._classes.DecisionTreeClassifier.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Test binary_classification_compas_sklearn.tree._classes.DecisionTreeClassifier.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested with regression_insurance_sklearn.ensemble._forest.ExtraTreesRegressor.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Test regression_insurance_sklearn.ensemble._gb.GradientBoostingRegressor.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.ensemble._gb.GradientBoostingClassifier.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_sklearn.ensemble._gb.GradientBoostingClassifier.sav with Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.ensemble._forest.RandomForestClassifier.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_sklearn.ensemble._forest.RandomForestClassifier.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.linear_model._perceptron.Perceptron.sav for Docker. Working as expected. Report Generated.

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.linear_model._perceptron.Perceptron.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_categoricalcrossentropy_keras.engine.sequential.Sequential.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_crossentropy_keras.engine.sequential.Sequential.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_hinge_keras.engine.sequential.Sequential.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_xgboost.sklearn.XGBClassifier.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_xgboost.sklearn.XGBClassifier.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_xgboost.sklearn.XGBRegressor.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_logistic_xgboost.core.Booster.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_lightgbm.sklearn.LGBMClassifier.sav for Docker. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Integration Test Passed

image

**Review by imda-kwokwk — APPROVED** [review]
looks good, please proceed

**Review by kimeetok — APPROVED** [review]

**Pull request merged**
