### PR TITLE
Modified code to process message in a seperate process initially inst…

### PR DESCRIPTION
**Pull request by imda-lionelteo**
…ead of processing algorithm instance at a later time. Added a new enum to allow control through the multiprocess queue.

## Description

Fixed critical bug where algorithm instance hangs when using certain model.

## Motivation and Context

Algorithm instance hangs when using certain model while performing tests.

## Type of Change
- fix: A bug fix

## How to Test

Testing is still ongoing

## Checklist

Please check all the boxes that apply to this pull request using "x":

- [x]  I have tested the changes locally and verified that they work as expected.
- [ ]  I have added or updated the necessary documentation (README, API docs, etc.).
- [ ]  I have added appropriate unit tests or functional tests for the changes made.
- [x]  I have followed the project's coding conventions and style guidelines.
- [ ]  I have rebased my branch onto the latest commit of the main branch.
- [ ]  I have squashed or reorganized my commits into logical units.
- [ ]  I have added any necessary dependencies or packages to the project's build configuration.
- [ ]  I have performed a self-review of my own code.
- [ ]  I have read, understood and agree to the Developer Certificate of Origin below, which this project utilises.

## Screenshots (if applicable)

[If the changes involve visual modifications, include screenshots or GIFs that demonstrate the changes.]

## Additional Notes

[Add any additional information or context that might be relevant to reviewers.]

<details>
  <summary>Developer Certificate of Origin</summary>

 ```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
 ```
</details>

### CODE REVIEW

**Review by imda-kelvinkok — APPROVED** [review]

**Review by imda-benedictlee — APPROVED** [review]
Tested with AI Verify Summary Report For Classification Model Template. All AI Test Passed and Report Generated.

image

image

image

image

Proceeding to test Backend Test

**Comment by imda-benedictlee** [comment]
@thomasimda requires testing of all supported models via UI. Will be testing all supported models via UI.

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.ensemble._bagging.BaggingClassifier.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_sklearn.ensemble._forest.RandomForestClassifier.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_sklearn.linear_model._base.LinearRegression.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.tree._classes.DecisionTreeClassifier.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_sklearn.tree._classes.DecisionTreeClassifier.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_sklearn.ensemble._forest.ExtraTreesRegressor.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_sklearn.ensemble._gb.GradientBoostingRegressor.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.ensemble._gb.GradientBoostingClassifier.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested with binary_classification_compas_sklearn.ensemble._gb.GradientBoostingClassifier.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_sklearn.ensemble._forest.RandomForestRegressor.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.ensemble._forest.RandomForestClassifier.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_sklearn.ensemble._forest.RandomForestClassifier.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.ensemble._bagging.BaggingClassifier.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_sklearn.ensemble._bagging.BaggingClassifier.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.linear_model._perceptron.Perceptron.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.linear_model._perceptron.Perceptron.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested /binary_classification_compas_sklearn.linear_model._perceptron.Perceptron.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_categoricalcrossentropy_keras.engine.sequential.Sequential.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested with binary_classification_compas_crossentropy_keras.engine.sequential.Sequential.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_hinge_keras.engine.sequential.Sequential.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_xgboost.sklearn.XGBClassifier.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_xgboost.sklearn.XGBClassifier.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_xgboost.sklearn.XGBRegressor.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_logistic_xgboost.core.Booster.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_lightgbm.sklearn.LGBMClassifier.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.ensemble._bagging.BaggingClassifier.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.ensemble._bagging.BaggingClassifier.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_sklearn.ensemble._forest.RandomForestClassifier.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_sklearn.linear_model._base.LinearRegression.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.tree._classes.DecisionTreeClassifier.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.ensemble._bagging.BaggingClassifier.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_sklearn.ensemble._forest.RandomForestClassifier.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_sklearn.linear_model._base.LinearRegression.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.tree._classes.DecisionTreeClassifier.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_sklearn.tree._classes.DecisionTreeClassifier.sav with Python 3.11. Working as expected. Report Generated.

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_sklearn.ensemble._forest.ExtraTreesRegressor.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.ensemble._gb.GradientBoostingClassifier.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_sklearn.ensemble._gb.GradientBoostingClassifier.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_sklearn.ensemble._forest.RandomForestRegressor.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.ensemble._forest.RandomForestClassifier.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_sklearn.ensemble._forest.RandomForestClassifier.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.ensemble._bagging.BaggingClassifier.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_sklearn.ensemble._bagging.BaggingClassifier.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_sklearn.linear_model._perceptron.Perceptron.sav. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_sklearn.linear_model._perceptron.Perceptron.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_categoricalcrossentropy_keras.engine.sequential.Sequential.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_crossentropy_keras.engine.sequential.Sequential.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_hinge_keras.engine.sequential.Sequential.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_xgboost.sklearn.XGBClassifier.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested multiclass_classification_loan_xgboost.sklearn.XGBClassifier.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested regression_insurance_xgboost.sklearn.XGBRegressor.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Comment by imda-benedictlee** [comment]
Tested binary_classification_compas_logistic_xgboost.core.Booster.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Review by imda-benedictlee — APPROVED** [review]
Tested regression_insurance_sklearn.ensemble._forest.ExtraTreesRegressor.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

Tested regression_insurance_sklearn.ensemble._forest.RandomForestRegressor.sav with Python 3.11. Working as expected. Report Generated.

image

image

image

**Review by imda-kelvinkok — APPROVED** [review]

**Pull request merged**
